# Generated by Django 3.2 on 2026-01-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travellersin_website_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_numbers',
            field=models.CharField(default='', max_length=200),
        ),
    ]
