# Generated by Django 3.2 on 2026-02-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travellersin_website_backend', '0003_auto_20260113_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='razorpay_signature',
        ),
        # migrations.AddField(
        #     model_name='booking',
        #     name='booking_source',
        #     field=models.CharField(default='online', max_length=20),
        # ),
    ]
