# Generated by Django 3.2 on 2026-02-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travellersin_website_backend', '0004_auto_20260205_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_source',
            field=models.CharField(default='online', max_length=20),
        ),
    ]
