# Generated by Django 3.2 on 2026-02-05 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travellersin_website_backend', '0005_booking_booking_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('billing_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('amount_paid', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('payment_type', models.CharField(default='cash', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='Travellersin_website_backend.booking')),
            ],
        ),
    ]
