# Generated by Django 3.2.12 on 2026-02-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travellersin_website_backend', '0006_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='billing',
            name='payment_gateway_ref_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='status',
            field=models.CharField(default='success', max_length=20),
        ),
        migrations.AddField(
            model_name='billing',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='booking',
            name='id_proof_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id_proof_file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id_proof_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
