# Generated by Django 3.2.12 on 2026-02-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travellersin_website_backend', '0007_auto_20260206_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Exterior', 'Exterior'), ('Lobby', 'Lobby'), ('Rooms', 'Rooms'), ('Dining', 'Dining'), ('Events', 'Events')], max_length=50)),
                ('order', models.IntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
