# Generated by Django 3.2.12 on 2026-02-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travellersin_website_backend', '0009_auto_20260219_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
