# Generated by Django 3.2 on 2026-07-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travellersin_website_backend', '0011_auto_20260701_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
