# Generated by Django 3.2 on 2026-07-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travellersin_website_backend', '0012_rooms_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='lastmodified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='lastmodified_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='lastmodified_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
